### ISSUE TITLE
Query regarding implementation of DTLZ test suit

### ISSUE THREAD

**Issue by Mathi50** [fcampelo/DEMO#6]
Dear Felipe,  
I tried to implement DTLZ test problems using the following code,

https://github.com/fcampelo/DEMO/blob/master/Octave-Matlab/DTLZ/dtlz1.m

I could not run the code with 2 or 3 objectives with 3 variables. I am getting the error like,

Error using dtlz_1 (line 27)
Using k = 5, it is required that the number of dimensions be n = (M - 1) + k = 10 in this case. 

Can you help me to clear this? 

Thank you,
Chandana
PhD student

**Comment by AmirHosein-Ahf** [comment]
It's because of the definition of the DTLZ functions. 
The NO of objectives and No of variables are not independent.
It means that the 3Obj problem has 6 variables

**Comment by fcampelo** [comment]
Hi Chandana,

@AmirHosein-Ahf is right. Please check the explanation of the DTLZ functions, e.g., here: <https://esa.github.io/pagmo2/docs/cpp/problems/dtlz.html> ; or the original definitions here: <https://link.springer.com/chapter/10.1007/1-84628-137-7_6>. 

Cheers,
Felipe
